'use strict';

exports.__esModule = true;
var CART_PREFIX = exports.CART_PREFIX = '@@CART/';

var FETCH_CART = exports.FETCH_CART = {
    'REQUEST': CART_PREFIX + 'FETCH_REQUEST',
    'SUCCESS': CART_PREFIX + 'FETCH_SUCCESS',
    'FAILURE': CART_PREFIX + 'FETCH_FAILURE',
    'LOADING': CART_PREFIX + 'FETCH_LOADING'
};

var REMOVE_CART_ITEM = exports.REMOVE_CART_ITEM = {
    'REQUEST': CART_PREFIX + 'REMOVE_ITEM_REQUEST',
    'SUCCESS': CART_PREFIX + 'REMOVE_ITEM_SUCCESS',
    'FAILURE': CART_PREFIX + 'REMOVE_ITEM_FAILURE',
    'LOADING': CART_PREFIX + 'REMOVE_ITEM_LOADING'
};