export var CART_PREFIX = '@@CART/';

export var FETCH_CART = {
    'REQUEST': CART_PREFIX + 'FETCH_REQUEST',
    'SUCCESS': CART_PREFIX + 'FETCH_SUCCESS',
    'FAILURE': CART_PREFIX + 'FETCH_FAILURE',
    'LOADING': CART_PREFIX + 'FETCH_LOADING'
};

export var REMOVE_CART_ITEM = {
    'REQUEST': CART_PREFIX + 'REMOVE_ITEM_REQUEST',
    'SUCCESS': CART_PREFIX + 'REMOVE_ITEM_SUCCESS',
    'FAILURE': CART_PREFIX + 'REMOVE_ITEM_FAILURE',
    'LOADING': CART_PREFIX + 'REMOVE_ITEM_LOADING'
};