export const CART_PREFIX = '@@CART/'

export const FETCH_CART = {
    'REQUEST': CART_PREFIX + 'FETCH_REQUEST',
    'SUCCESS': CART_PREFIX + 'FETCH_SUCCESS',
    'FAILURE': CART_PREFIX + 'FETCH_FAILURE'
}

export const REMOVE_CART_ITEM = {
    'REQUEST': CART_PREFIX + 'REMOVE_ITEM_REQUEST',
    'SUCCESS': CART_PREFIX + 'REMOVE_ITEM_SUCCESS',
    'FAILURE': CART_PREFIX + 'REMOVE_ITEM_FAILURE'
}
